-- Run this entire file in Supabase SQL Editor.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text not null,
  role text not null check (role in ('admin', 'barangay_official', 'resident')),
  department text,
  position text,
  phone text,
  avatar_url text,
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists department text;
alter table public.profiles add column if not exists position text;
alter table public.profiles add column if not exists phone text;
alter table public.profiles add column if not exists avatar_url text;

alter table public.profiles drop constraint if exists profiles_role_check;
update public.profiles
set role = 'barangay_official'
where role = 'official';
alter table public.profiles add constraint profiles_role_check check (role in ('admin', 'barangay_official', 'resident'));

alter table public.profiles enable row level security;
drop policy if exists "users can read own profile" on public.profiles;
create policy "users can read own profile" on public.profiles for select to authenticated using (auth.uid() = id);
create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  request_id text generated always as ('DOC-' || lpad(id::text, 4, '0')) stored unique,
  resident_name text not null,
  document_type text not null,
  purpose text,
  applicant_address text,
  applicant_contact text,
  applicant_date_of_birth date,
  applicant_place_of_birth text,
  applicant_civil_status text,
  business_name text,
  business_address text,
  date_requested date not null default current_date,
  status text not null default 'Pending' check (status in ('Pending', 'In Progress', 'Processing', 'Approved', 'Rejected', 'Resolved')),
  processor text,
  scheduled_date date,
  scheduled_time time,
  requester_id uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.concerns (
  id bigint generated by default as identity primary key,
  concern_id text generated always as ('CON-' || lpad(id::text, 3, '0')) stored unique,
  category text not null,
  priority text not null default 'Medium' check (priority in ('Low', 'Medium', 'High', 'Critical')),
  title text not null,
  description text,
  submitted_by text not null,
  submitted_at date not null default current_date,
  status text not null default 'Pending' check (status in ('Pending', 'Open', 'In Progress', 'Escalated', 'Resolved')),
  reporter_id uuid references auth.users(id),
  latitude double precision,
  longitude double precision,
  created_at timestamptz not null default now()
);
create table if not exists public.residents (
  id bigint generated by default as identity primary key,
  resident_id text generated always as ('RES-' || lpad(id::text, 3, '0')) stored unique,
  full_name text not null,
  address text not null,
  household text not null default 'UNASSIGNED',
  email text,
  phone text,
  age integer not null check (age between 1 and 120),
  gender text not null check (gender in ('Female', 'Male', 'Other')),
  status text not null default 'Pending' check (status in ('Verified', 'Pending', 'Inactive')),
  resident_since date not null default current_date,
  created_at timestamptz not null default now()
);
alter table public.residents add column if not exists email text;
alter table public.residents add column if not exists phone text;

alter table public.documents add column if not exists requester_id uuid references auth.users(id);
alter table public.documents add column if not exists purpose text;
alter table public.documents add column if not exists applicant_address text;
alter table public.documents add column if not exists applicant_contact text;
alter table public.documents add column if not exists applicant_date_of_birth date;
alter table public.documents add column if not exists applicant_place_of_birth text;
alter table public.documents add column if not exists applicant_civil_status text;
alter table public.documents add column if not exists business_name text;
alter table public.documents add column if not exists business_address text;
alter table public.documents add column if not exists scheduled_date date;
alter table public.documents add column if not exists scheduled_time time;
alter table public.concerns add column if not exists reporter_id uuid references auth.users(id);
alter table public.concerns add column if not exists description text;
alter table public.concerns add column if not exists latitude double precision;
alter table public.concerns add column if not exists longitude double precision;

alter table public.documents drop constraint if exists documents_status_check;
alter table public.documents add constraint documents_status_check check (status in ('Pending', 'In Progress', 'Processing', 'Approved', 'Rejected', 'Resolved'));
alter table public.concerns drop constraint if exists concerns_status_check;
alter table public.concerns add constraint concerns_status_check check (status in ('Pending', 'Open', 'In Progress', 'Escalated', 'Resolved'));
create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  category text not null,
  status text not null default 'Active' check (status in ('Active', 'Expired')),
  title text not null,
  description text,
  author text not null,
  published_at date not null default current_date,
  audience text not null default 'All Residents',
  author_email text,
  created_at timestamptz not null default now()
);

create table if not exists public.weather_alerts (
  id bigint generated by default as identity primary key,
  alert_type text not null,
  title text not null,
  description text not null,
  severity text not null default 'Open',
  author text,
  issued_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.announcements add column if not exists author_email text;
alter table public.announcements add column if not exists description text;
alter table public.weather_alerts add column if not exists author text;

alter table public.documents enable row level security;
alter table public.concerns enable row level security;
alter table public.announcements enable row level security;
alter table public.weather_alerts enable row level security;

create index if not exists documents_requester_id_idx on public.documents (requester_id);
create index if not exists documents_status_idx on public.documents (status);
create index if not exists concerns_reporter_id_idx on public.concerns (reporter_id);
create index if not exists concerns_status_idx on public.concerns (status);
create index if not exists concerns_category_idx on public.concerns (category);
create index if not exists announcements_status_idx on public.announcements (status);
create index if not exists weather_alerts_issued_at_idx on public.weather_alerts (issued_at desc);

-- The Flask service-role key bypasses RLS. These read policies support future authenticated clients.
drop policy if exists "authenticated documents read" on public.documents;
create policy "authenticated documents read" on public.documents for select to authenticated using (true);
drop policy if exists "authenticated concerns read" on public.concerns;
create policy "authenticated concerns read" on public.concerns for select to authenticated using (true);
drop policy if exists "authenticated announcements read" on public.announcements;
create policy "authenticated announcements read" on public.announcements for select to authenticated using (true);
drop policy if exists "authenticated weather alerts read" on public.weather_alerts;
create policy "authenticated weather alerts read" on public.weather_alerts for select to authenticated using (true);

insert into public.documents (resident_name, document_type, date_requested, status, processor)
select seed.resident_name, seed.document_type, seed.date_requested, seed.status, seed.processor
from (values
  ('Maria Santos', 'Barangay Clearance', '2026-09-04'::date, 'Approved', 'Admin Flores'),
  ('Pedro Villanueva', 'Certificate of Indigency', '2026-09-05'::date, 'Processing', 'Admin Flores'),
  ('Ana Reyes', 'Certificate of Residency', '2026-09-05'::date, 'Pending', null),
  ('Carlos Mendoza', 'Business Clearance', '2026-09-06'::date, 'Approved', 'Admin Cruz'),
  ('Liza Torres', 'Barangay Clearance', '2026-09-07'::date, 'Rejected', 'Admin Flores'),
  ('Juan dela Cruz', 'Certificate of Indigency', '2026-09-07'::date, 'Processing', 'Admin Cruz'),
  ('Rosa Bautista', 'Certificate of Residency', '2026-09-08'::date, 'Pending', null)
) as seed(resident_name, document_type, date_requested, status, processor)
where not exists (
  select 1 from public.documents existing
  where existing.resident_name = seed.resident_name
    and existing.document_type = seed.document_type
    and existing.date_requested = seed.date_requested
);

insert into public.concerns (category, priority, title, submitted_by, submitted_at, status)
select seed.category, seed.priority, seed.title, seed.submitted_by, seed.submitted_at, seed.status
from (values
  ('Infrastructure', 'High', 'Pothole on main road near Purok 2', 'Juan dela Cruz', '2026-09-01'::date, 'Resolved'),
  ('Peace & Order', 'Medium', 'Noise disturbance at nighttime', 'Maria Santos', '2026-09-02'::date, 'Open'),
  ('Health & Sanitation', 'High', 'Garbage not collected in Purok 5', 'Ana Reyes', '2026-09-03'::date, 'Open'),
  ('Infrastructure', 'Medium', 'Street light malfunction at Blk 3', 'Carlos Mendoza', '2026-09-04'::date, 'In Progress'),
  ('Social Services', 'Critical', 'Request for food assistance', 'Pedro Villanueva', '2026-09-05'::date, 'Escalated'),
  ('Health & Sanitation', 'High', 'Stagnant water breeding mosquitoes', 'Liza Torres', '2026-09-06'::date, 'Open')
) as seed(category, priority, title, submitted_by, submitted_at, status)
where not exists (
  select 1 from public.concerns existing where existing.title = seed.title
);

insert into public.announcements (category, status, title, author, published_at, audience)
select seed.category, seed.status, seed.title, seed.author, seed.published_at, seed.audience
from (values
  ('Assembly', 'Active', 'Barangay Assembly — September 15, 2026', 'Kap. Ramirez', '2026-09-08'::date, 'All Residents'),
  ('Health', 'Active', 'Free Medical Mission — September 12, 2026', 'Health Officer', '2026-09-07'::date, 'All Residents'),
  ('Emergency', 'Active', 'Typhoon Preparedness Advisory — Signal #1', 'DRRMC', '2026-09-06'::date, 'All Residents'),
  ('Livelihood', 'Active', 'Livelihood Training Program — Registration Open', 'PESO Office', '2026-09-04'::date, '18–45 yrs'),
  ('Social Services', 'Expired', 'Senior Citizens'' ID Renewal Schedule', 'OSCA', '2026-09-02'::date, 'Seniors 60+')
) as seed(category, status, title, author, published_at, audience)
where not exists (
  select 1 from public.announcements existing where existing.title = seed.title
);

insert into public.weather_alerts (alert_type, title, description, severity, issued_at)
select seed.alert_type, seed.title, seed.description, seed.severity, seed.issued_at
from (values
  ('ACTIVE ADVISORY', 'Typhoon Preparedness Advisory — Signal #1', 'PAGASA has raised Tropical Cyclone Wind Signal No. 1 over Leyte. Prepare emergency supplies and monitor official advisories.', 'Escalated', '2026-09-08 07:30:00+08'::timestamptz)
) as seed(alert_type, title, description, severity, issued_at)
where not exists (
  select 1 from public.weather_alerts existing where existing.title = seed.title
);
